### ISSUE TITLE
Broken link in the website index.html

### ISSUE THREAD

**Issue by jspaezp** [cole-trapnell-lab/garnett#1]
Hello !

I was going through the webside and documentation and noticed the website has a broken link because it is missing the `{{site.baseurl}}` in the reference here:

https://github.com/cole-trapnell-lab/garnett/blob/5cd62754203609a4cdf674238b0c4fb10e6e8358/index.html#L24

where it should be `<a href = "{{site.baseurl}}/docs/#1b-train-your-own-classifier">`

Looking forward to trying out the package in the near future !
Kindest wishes !
Sebastian

**Comment by hpliner** [comment]
Nice catch! Just pushed the fix, should deploy shortly

**Comment by hpliner** [comment]
Should be all set now. Thanks!!
