### ISSUE TITLE
Classification based upon AND / OR gene expression?

### ISSUE THREAD

**Issue by jma1991** [cole-trapnell-lab/garnett#11]
Hello,

I would like to use Garnett to classify some cells and I wanted to ask whether the genes I list for each cell type are all required to be expressed or just some of them? For example, we know of a cell type which is marked by the expression of both Gene A and B, but we are not interested in cells which express only one of these markers.

Regards,
James

**Comment by hpliner** [comment]
Hi James,

Garnett will develop and aggregated score for each cell based on the totality of the genes included in the marker file. So having both expressed will give a cell a higher chance of being chosen as a training cell, but having both expressed is not a requirement. In short, it's more of an OR situation. Hope this helps,

Hannah

**Comment by VPetukhov** [comment]
Hi @hpliner ,
Did you consider extending the markup language to allow a user to choose the behaviour? Indeed, both "OR" and "AND" cases are very popular during annotation.
