### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by PertuyF** [cole-trapnell-lab/garnett#13]
Hi there!

Do you guys plan to package this tool in any way? (e.g. Bioconductor, or tag + github tarball?)
I have users interested into Garnett, but I am concerned regarding reproducibility when installing latest commit from this repo using devtools.
It would be really nice if we could rely on fixed versions!

**Comment by hpliner** [comment]
Thanks for getting in touch. Yes, we do tend to package the tool (at least with release tags and possibly with Bioconductor), but we are in the process of transitioning from a monocle dependency to a monocle3 dependency (monocle 3 was just released), so there may be a delay. I'm happy to set a release tag now for use immediately though.

**Comment by PertuyF** [comment]
Thanks for the release @hpliner !
