### ISSUE TITLE
classifier for Linnarson brain cell type

### ISSUE THREAD

**Issue by hhhcce** [cole-trapnell-lab/garnett#21]
To whom it may concern,

Nice paper! I was wondering whether the pre-trained classifier for Linarsson's brain cell type paper mentioned in the supplementary material is available in your Shiny website. I managed to download the marker genes from your Nature method's paper. 

Thanks!

**Comment by hpliner** [comment]
Hello,

The Linarsson mouse brain classifier is now up on the website and incorporated into the shiny app.

Bes,t
Hannah
