### ISSUE TITLE
bug in get_feature_genes() function

### ISSUE THREAD

**Issue by a-solovyev12** [cole-trapnell-lab/garnett#22]
Hello, 

I was running the `get_feature_genes()` function with test input and default parameters (as in [tutorial](https://cole-trapnell-lab.github.io/garnett/docs/#viewing-the-classification-genes)) when the following error popped up: 

```
Error in do.call("cbind", feature_genes) : second argument must be a list
Calls: get_feature_genes -> as.data.frame -> as.matrix -> do.call
```
Apparently, `feature_genes` is a vector rather than a list and just needs to be wrapped into a list function. Could you please fix this? 

Thanks!

**Comment by hpliner** [comment]
Thanks for the report, I believe this is now fixed in the latest version. Please reinstall and give it another try!

**Comment by a-solovyev12** [comment]
@hpliner, thanks a lot for fixing this. Could you please make a release with an updated version? We built a command line interface for Garnett as a bioconda package and need to update the recipe.

**Comment by hpliner** [comment]
@a-solovyev12 Sorry for the delay, I just created a new release, 0.1.13

**Comment by a-solovyev12** [comment]
@hpliner, thank you :)
