### ISSUE TITLE
Setting cell type as subtype of self causes check_markers to hang

### ISSUE THREAD

**Issue by RobertAlpin** [cole-trapnell-lab/garnett#23]
Hello,
In my markerfile, I had accidentally listed a cell type as:

```
>CARDIOMYOCYTES
expressed: TNNI3, TNNT2, ACTN2
subtype of: CARDIOMYOCYTES
```

And using check_markers as usual caused it to 'load' infinitely at this step:

```
Error in is.data.frame(marker_check_df) : object 'marker_check' not found
> marker_check <- check_markers(cds, marker_file_path,
+                               db='none',
+                               cds_gene_id_type = "SYMBOL",
+                               marker_file_gene_id_type = "SYMBOL")
There are 9 cell type definitions
```

Out of curiosity I went back and did the same thing with another cell type in my markerfile, and got the same issue. I feel that this might be worth an error message.

**Comment by hpliner** [comment]
Thanks for the suggestion, implemented in the latest!
