### ISSUE TITLE
Classifier training issue

### ISSUE THREAD

**Issue by jentiger82** [cole-trapnell-lab/garnett#24]
I created a classifier file based on marker gene expression using a published data set. Whenever, I try to train the classifier using the same CDS file, I get the following error stating "No cell types with sufficient examples":

3: In train_glmnet(cds_sub, classifier, v, training_sample, min_observations = min_observations,  :
  No cell types with sufficient examples

What does this mean? Are there too many ambiguous cells?

Thanks, Jenny

**Comment by hpliner** [comment]
In general, this means that that there are too many ambiguous cells, though I have recently fixed a bug that may have inflated the number of ambiguous cells, so I recommend reinstalling and trying again. If you continue to have issues with insufficient examples, take a look at your marker plot and make sure your markers aren't too overlapping. See the website for how!

**Comment by hpliner** [comment]
Closing, request to reopen if you have follow up questions
