### ISSUE TITLE
Error in classify_cells: object 'excluded_cells' not found

### ISSUE THREAD

**Issue by VPetukhov** [cole-trapnell-lab/garnett#26]
In the function [`classify_cells`](https://github.com/cole-trapnell-lab/garnett/blob/master/R/classify_cells.R) variable [`excluded_cells`](https://github.com/cole-trapnell-lab/garnett/blob/master/R/classify_cells.R#L189) is never defined, which cause crash.

**Comment by hpliner** [comment]
Thanks for the report, I believe this is now fixed, go ahead and reinstall and if the error persists, reopen!
