### ISSUE TITLE
Potential bug in implementation of tfidf

### ISSUE THREAD

**Issue by VPetukhov** [cole-trapnell-lab/garnett#31]
In the [`tfidf`](https://github.com/cole-trapnell-lab/garnett/blob/master/R/train_cell_classifier.R#L585) function you use `log(1 + ncol(ncounts) / Matrix::rowSums(ncounts))` as the idf term. Though in [classic idf](https://en.wikipedia.org/wiki/Tf%E2%80%93idf#Inverse_document_frequency_2) you need to normalize on number of documents, but not total counts over documents: `log(1 + ncol(ncounts > 0) / Matrix::rowSums(ncounts))`. Does it have internal meaning or is it just a bug?

In the second case, the whole function can be optimized with 2-fold speed up (using "inverse document frequency smooth" method):
```R
tfidf <- function(input_cds) {
  nfreqs <- exprs(input_cds)
  nfreqs@x <- nfreqs@x / rep.int(Matrix::colSums(nfreqs), diff(nfreqs@p))
  nfreqs <- Matrix::t(nfreqs)
  nfreqs@x <- nfreqs@x * rep(log(1 + nrow(nfreqs) / 
      (Matrix::colSums(nfreqs > 0) + 1)), diff(nfreqs@p))
  return(nfreqs)
}
```

Just in case, the logic of the function above exactly corresponds to the following call of tfidf from `quanteda` package (only works faster):
```R
quanteda::as.dfm(exprs(input_cds))
quanteda::dfm_tfidf(dfq, scheme_tf="prop", smoothing=1, base=exp(1))
```

**Comment by hpliner** [comment]
Because the ncounts object is derived like this:
```
ncounts <- exprs(input_cds)
ncounts <- ncounts[Matrix::rowSums(ncounts) != 0,]
```
I think the implementation does count the number of documents... and the ncol should be counting, not summing counts. Does that make sense?

On your pull request and other issues, I'm hoping to get to them early next week.

**Comment by VPetukhov** [comment]
Yes, `ncol` is counting, but `rowSums(cm)` gives you sum count over all documents, but not number of documents containing this word.

**Comment by hpliner** [comment]
It seems like it's the same... unless I'm missing something
```
> tfidf_current <- function(input_cds) {
+   ncounts <- counts(input_cds)
+   ncounts <- ncounts[Matrix::rowSums(ncounts) != 0,]
+   nfreqs <- ncounts
+   nfreqs@x <- ncounts@x / rep.int(Matrix::colSums(ncounts), diff(ncounts@p))
+   tf_idf_counts <- nfreqs * log(1 + ncol(ncounts) / Matrix::rowSums(ncounts))
+   Matrix::t(tf_idf_counts)
+ }
> tfidf_prop <- function(input_cds) {
+   ncounts <- counts(input_cds)
+   ncounts <- ncounts[Matrix::rowSums(ncounts) != 0,]
+   nfreqs <- ncounts
+   nfreqs@x <- ncounts@x / rep.int(Matrix::colSums(ncounts), diff(ncounts@p))
+   tf_idf_counts <- nfreqs * log(1 + ncol(ncounts > 0) / Matrix::rowSums(ncounts))
+   Matrix::t(tf_idf_counts)
+ }
> x <- tfidf_current(test_cds)
> y <- tfidf_prop(test_cds)
> identical(x, y)
[1] TRUE
```

**Comment by VPetukhov** [comment]
It's not 
```r
tf_idf_counts <- nfreqs * log(1 + ncol(ncounts > 0) / Matrix::rowSums(ncounts))
```
but
```r
tf_idf_counts <- nfreqs * log(1 + ncol(ncounts) / Matrix::rowSums(ncounts > 0))
```

**Comment by hpliner** [comment]
Ah, I see what you're saying. Yes, that's a bug - a relic of using binary matrices when it's the same. Fixed now
