### ISSUE TITLE
cross species cell type transfer

### ISSUE THREAD

**Issue by justinesjw** [cole-trapnell-lab/garnett#33]
Hi, 

Thank you for the Garnett it has been very useful. 

Is it possible to train the classifier on mouse data and classify cells from human data?

Many thanks, 
Justine

**Comment by hpliner** [comment]
Hi Justine,

Glad it's been useful. We have had some success doing this. The main obstacle to trying it is the different gene names. The way I've done it before is make a "mouse-ified" human cds object or vice-versa (basically a mouse data cds with human gene names). Here's some code I've used in the past to generate a mouse-human gene table using biomaRt:

```
require("biomaRt")
human = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl")
genesV2 = getLDS(attributes = c("ensembl_gene_id"), 
                 filters = "ensembl_gene_id", 
                 values = fData(human_cds)$gene , 
                 mart = human, 
                 attributesL = c("ensembl_gene_id"), 
                 martL = mouse, 
                 uniqueRows=T)
```
Then a bunch of merges should get you a gene table and expression matrix with the right gene names that you can feed into new_cell_data_set.

Hope this helps,
Hannah

**Comment by justinesjw** [comment]
Hi Hannah, 

Thanks!

However, we realized that getLDS() do not convert all genes.
We were able to convert more genes using this library. :) 
http://www.informatics.jax.org/downloads/reports/HMD_HumanPhenotype.rpt

Cheers! 
Justine

**Comment by hpliner** [comment]
Looks like this is resolved, reply or reopen if this continues to be an issue.
