### ISSUE TITLE
installation using github file fails with error due to R version in which VGAM was built...

### ISSUE THREAD

**Issue by SathiyaNManivannan** [cole-trapnell-lab/garnett#35]
**Describe the bug**
I tried to reinstall Garnett in R using devtools. But I get the following error when the package is complied and packed for lazy loading

** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'VGAM' was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package 'garnett'
* removing 'C:/Users/sxm165/Documents/R/win-library/3.6/garnett'

**To Reproduce**
devtools::install_github("cole-trapnell-lab/garnett")

**Expected behavior**
downloads and begins to install the package, but fails to complete installation: 

Error: Failed to install 'garnett' from GitHub:
  (converted from warning) installation of package ‘C:/Users/sxm165/AppData/Local/Temp/Rtmp6ftf7T/file3c247e6bb51/garnett_0.1.14.tar.gz’ had non-zero exit status

Might have something to do with warnings being turned errors in yml file.
**Screen shot**
![image](https://user-images.githubusercontent.com/33238610/72382362-1bcd3500-36e7-11ea-8848-bae3999e1e03.png)

**Comment by hpliner** [comment]
Hello, Looks to me like it doesn't like your VGAM version. Can you try reinstalling VGAM using install.packages("VGAM") and then repeat the Garnett install?

**Comment by hpliner** [comment]
I'm going to close, reply or reopen if this continues to be an issue.
