### ISSUE TITLE
Garnett Installtion Error

### ISSUE THREAD

**Issue by pbpayal** [cole-trapnell-lab/garnett#37]
I am using Monocle 3 and R 3.6. For Garnett, do I need to install monocle? But that's not compatible with R 3.6. So how to work with Garnett and Monocle3 together?

`> devtools::install_github("cole-trapnell-lab/garnett")
Downloading GitHub repo cole-trapnell-lab/garnett@master
Skipping 7 packages not available: monocle, AnnotationDbi, Biobase, DelayedArray, DelayedMatrixStats, org.Hs.eg.db, org.Mm.eg.db
Skipping 6 packages ahead of CRAN: plyr, rlang, digest, stringi, cli, vctrs
Installing 8 packages: monocle, doParallel, forcats, glmnet, rly, foreach, iterators, shape`
`Error: Failed to install 'garnett' from GitHub:
  (converted from warning) package ‘monocle’ is not available (for R version 3.6.2)`

**Comment by hpliner** [comment]
Hello, Be sure you're following the instructions for the monocle3 version of Garnett - in the above code, you're installing the monocle2 version. See here for the instructions: https://cole-trapnell-lab.github.io/garnett/docs_m3/#installing-garnett
