### ISSUE TITLE
Error: Path '' does not exist train_cell_classifier

### ISSUE THREAD

**Issue by liliay** [cole-trapnell-lab/garnett#39]
Hi there, 
I am actually using Garnett package and i want to train my own classifier. 
I am running this portion of code as described in the tutorial : 
library(garnett)
library(org.Hs.eg.db)
set.seed(260)
marker_file_path <- system.file("/cloud-data/eu-ngs/Lilia/garnett-trapnell/extdata/","/cloud-data/eu-ngs/Lilia/garnett-trapnell/hsPBMC_markers.txt",
                                package = "garnett")
classifier <- train_cell_classifier(cds = cds_p13,
                                         marker_file = marker_file_path,
                                         db=org.Hs.eg.db,
                                    min_observations = 10, 
                                         cds_gene_id_type = "ENSEMBL",
                                         num_unknown = 50,
                                         marker_file_gene_id_type = "ENSEMBL")
And the message error I get is : 
Error: Path '' does not exist

Attached to this request you will find all the informations about my R session. I tried to update the packages but nothing changed. Is there any specific package I need to update ? 
![session_info](https://user-images.githubusercontent.com/45742503/76440644-710f8500-63be-11ea-9df8-26a440468d82.PNG)
![session_info_2](https://user-images.githubusercontent.com/45742503/76440647-7240b200-63be-11ea-8866-12c55df1f51a.PNG)

Thanks in advance to anyone who could guide me to solve this issue.

**Comment by hpliner** [comment]
This looks like an issue with the path to the marker file. Can you modify the marker_file_path so that it is a simple string path to the file? I.e. "Documents/marker_file.txt"

**Comment by hpliner** [comment]
I'm going to close due to lack of response, if this is still an issue, please reopen!
