### ISSUE TITLE
human developing brain

### ISSUE THREAD

**Issue by Crockol** [cole-trapnell-lab/garnett#4]
Please provide the following info when submitting a new classifier:

Species:
Tissue/sample: human fetal brain
Author(s): Nicolò Caporale
Data source (if you generated the data, indicate yourself): 
I used public available papers and datasets to generate a marker file with the gene signatures of the different cell types in the developing human brain
Published? (if so provide DOI): 
https://cells.ucsc.edu/?ds=cortex-dev
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5995803/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3668182/
https://www.ncbi.nlm.nih.gov/pubmed/27350034
https://www.ncbi.nlm.nih.gov/pubmed/29217575

Any notes, including whether/how you have validated
This work was done in order to build a classifier for cortical brain organoids.
I am currently working and training the marker file on a cortical brain organoid that we differentiated in the lab for 50 days. 
https://www.biorxiv.org/content/early/2018/12/02/484741
I still have to verify how good it is and how generalisable the classifier is for other organoid protocols or other stages of differentiation. Thus I thought that submitting it to the community could facilitate its spread, testing and optimization.
If you have comments/critics/suggestions, contact me at nicolo.caporale@gmail.com

[MarkerDevelopingBrainRefined.txt](https://github.com/cole-trapnell-lab/garnett/files/2880300/MarkerDevelopingBrainRefined.txt)

**Comment by Crockol** [comment]
[MarkerDevelopingBrainRefined.txt](https://github.com/cole-trapnell-lab/garnett/files/2880293/MarkerDevelopingBrainRefined.txt)

**Comment by hpliner** [comment]
Thanks for this submission! Do you have the rdata file with the trained classifier to provide as well? You can save it using `save(classifier, file="classifier")`

**Comment by hpliner** [comment]
I'm going to close this, please reopen if you'd like to submit the classifier!
