### ISSUE TITLE
Cluster extend possible issue

### ISSUE THREAD

**Issue by lwhitmore** [cole-trapnell-lab/garnett#41]
Hi, 
I am unclear how cluster extend works.  I have a cluster (number 12) that has 257 unknown cells , 552 Monocyte cells and few other cells in other classifications (i.e B cells, T cells etc...) It seems like the cluster extend should be assigning these cells as monocytes but is not assigning them any classifications and is keeping them as Unknown cells. I am not understanding why this would happen. 
I have the  cluster_extend_max_frac_unknown = 1.  

Thanks for your help!
Leanne

**Comment by hpliner** [comment]
Apologies for the delay. How many cells are in the other classifications? Using the default cluster_extend_max_frac_incorrect of 0.1, if more than 10% of classified cells are something else (55 ish) then the cluster won't be extended.

**Comment by lwhitmore** [comment]
Not a problem! Even though when I set cluster_extend_max_frac_incorrect to 0 I still have some unknowns (although there are less)

**Comment by lwhitmore** [comment]
Hey at re examining this it seems like the cluster_extend_max_frac_incorrect does work but only for clusters whose main class is not unknown, which makes sense.  Sorry for the mix up here.  

Thanks for your help!
Leanne

**Comment by hpliner** [comment]
Great, so ok to close?

**Comment by lwhitmore** [comment]
Yeah sounds good!
Thanks again!
