### ISSUE TITLE
Cell Type Similarity 

### ISSUE THREAD

**Issue by justinesjw** [cole-trapnell-lab/garnett#44]
Hi Garnett Team!

Many thanks for generating Garnett. It has been a great help to my research!

One question, if cell type A is predicted as very similar to cell type B, how many genes are they depending on? and is there a possible way to extract the genes and their ranking?

Also, may I know how does the marker list play a role in the analysis?

Many thanks and take care, 
Justine

**Comment by hpliner** [comment]
Hi Justine,

You can use the [get_feature_genes](https://cole-trapnell-lab.github.io/garnett/docs_m3/#viewing-the-classification-genes) function to see what genes are being used in the model and their coefficients.

The marker list plays quite an important role in that without good markers, Garnett tends not to work nearly as well. That said, if you have lots of good markers, adding more doesn't seem to change the outcome very much. If you're using the monocle3 version of Garnett, and have pre-classified training data, you can try the new [marker_free classifier](https://cole-trapnell-lab.github.io/garnett/docs_m3/#1c-train-a-marker-free-classifier) which removes dependence on markers.

In future, please post questions to the google group [here](https://groups.google.com/forum/#!forum/garnett-users) and only bug reports on the github so people can more easily find answers to similar questions! Thanks!

**Comment by hpliner** [comment]
Closing, reopen if still an issue
