### ISSUE TITLE
Wrong classification pattern depending on one marker

### ISSUE THREAD

**Issue by EliseAld** [cole-trapnell-lab/garnett#46]
Dear Garnett developpers,

We are a small group of bioinformaticians and currently testing your cell classification tool on public data. We got very surprising results, and wondered if you could help us with that.

Using our own markers list, we are implementing Garnett on three immune cells datasets : Azizi [PMID 29961579], Lambrecht [PMID 29988129], and Young [PMID 30093597]. We noticed that, depending on whether we include a gene or not in the list (more precisely if we add  FCGR3A to the list of markers for monocytes/macrophages), the following happens :

- The results are more or less identical with or without this marker for Lambrecht and Young datasets
- A vast majority of the cells are labelled as mast cells when adding FCGR3A for the Azizi dataset

We checked the expression patterns of FCGR3A and the correlation patterns, nothing striking came out. Actually the same happens when we add ACTA2 as a marker for fibroblasts : again a lot of cells are labelled as mast cells for the Azizi dataset (while it is more or less the same for Lambrecht and Young).

We'd be thrilled if you have any insight about it !!

**Comment by hpliner** [comment]
Hello,

It's a bit tough to say without more information, but I'm wondering if you've taken a look at the feature genes that are chosen in the two cases (get_feature_genes) to see if something sticks out. The times I've seen something similar before, it's been when a supposed marker is actually widely expressed - that causes training cells to be from all over - so then everything looks like that cell type, but sounds like you've ruled that out? 

A couple other things to check out: 
- if the data is particularly large, I recommend using a larger number of 'Unknown' cells (e.g. num_unknown = 1500) 
- you might try [marker-free classification](https://cole-trapnell-lab.github.io/garnett/docs_m3/#1c-train-a-marker-free-classifier) (new feature) on one dataset and then apply to the others to see if there is something quite different about the Azizi dataset

Hope this helps!

**Comment by hpliner** [comment]
Let me know if you have updates/further questions here
