### ISSUE TITLE
Error in adjacent_vertices(x, i, mode = if (directed) "out" else "all")

### ISSUE THREAD

**Issue by EleonoraLusito** [cole-trapnell-lab/garnett#50]
Hi, while doing the tutorial with pbmc data at https://cole-trapnell-lab.github.io/garnett/docs_m3/
during the classification (with/without markers) after doing str(pbmc_classifier) I found this Error (last lines): 

Formal class 'garnett_classifier' [package "garnett"] with 4 slots
  ..@ classification_tree:List of 10
  .. ..$ :List of 1
  .. .. ..$ root: 'igraph.vs' Named int [1:2] 2 3
  .. .. .. ..- attr(*, "names")= chr [1:2] "B cells" "T cells"
  .. .. .. ..- attr(*, "env")=<weakref> 
  .. .. .. ..- attr(*, "graph")= chr "d739d599-3f8b-45e9-a0b5-6852523798d1"
  .. ..$ :List of 1
  .. .. ..$ B cells: 'igraph.vs' Named int(0) 
  .. .. .. ..- attr(*, "names")= chr(0) 
  .. .. .. ..- attr(*, "env")=<weakref> 
  .. .. .. ..- attr(*, "graph")= chr "d739d599-3f8b-45e9-a0b5-6852523798d1"
  .. ..$ :List of 1
  .. .. ..$ T cells: 'igraph.vs' Named int [1:2] 4 5
  .. .. .. ..- attr(*, "names")= chr [1:2] "CD4 T cells" "CD8 T cells"
  .. .. .. ..- attr(*, "env")=<weakref> 
  .. .. .. ..- attr(*, "graph")= chr "d739d599-3f8b-45e9-a0b5-6852523798d1"
  .. ..$ :List of 1
  .. .. ..$ CD4 T cells: 'igraph.vs' Named int(0) 
  .. .. .. ..- attr(*, "names")= chr(0) 
  .. .. .. ..- attr(*, "env")=<weakref> 
  .. .. .. ..- attr(*, "graph")= chr "d739d599-3f8b-45e9-a0b5-6852523798d1"
  .. ..$ :List of 1
  .. .. ..$ CD8 T cells: 'igraph.vs' Named int(0) 
  .. .. .. ..- attr(*, "names")= chr(0) 
  .. .. .. ..- attr(*, "env")=<weakref> 
  .. .. .. ..- attr(*, "graph")= chr "d739d599-3f8b-45e9-a0b5-6852523798d1"
  .. ..$ :Error in adjacent_vertices(x, i, mode = if (directed) "out" else "all") : 
  At iterators.c:759 : Cannot create iterator, invalid vertex id, Invalid vertex id

Do you know something more about this bug and if/how it is possible to solve it? 

Thank you in advance

**Comment by hpliner** [comment]
Hello, Is this just an issue with the str function? Do you run into problems while continuing the tutorial?

**Comment by hpliner** [comment]
I'm going to close, if this is still an issue, please reopen
