### ISSUE TITLE
Test Garnett with custom marker file 

### ISSUE THREAD

**Issue by zznx** [cole-trapnell-lab/garnett#51]
Hi, recently I want to  test Garnett for automatic annotate the cell type of cluster which after single cell data analysis with Seurat.  I have marker gene list file and corresponding cell type, so I want to treat this marker list as my own custom classifier when I run the Garnett.  

So, my question is :  1.  is this reasonable? Or there have some other ideas?   2. how can I construct this coustom classifier , do you have releated code or document?  

Thanks a lot.

**Comment by hpliner** [comment]
I think all of your questions can be answered by reading our documentation website: https://cole-trapnell-lab.github.io/garnett/ If you still have questions, please post to https://groups.google.com/g/garnett-users
