### ISSUE TITLE
Classifier Questions

### ISSUE THREAD

**Issue by AlexCocker** [cole-trapnell-lab/garnett#52]
Firstly thank you for creating Garnett, I have found it simple to use so far and hope the list of classifiers keeps growing!

I am training a natural killer cell (NK) classifier based on a dataset where NK subsets were sorted prior to scRNAseq, so an ideal dataset for generating a classifier. However, the data is from a single donor who is HIV-1+. I know of other datasets which have similarly sorted NK populations, but they are from bulk RNA sequencing. Is it possible to incorporate bulk RNA sequencing data into the classifier training so it is representative of a wider range of donors and health statuses?

Also hopefully a simpler query; once I have run a marker free train_cell_classifier() how can I then pull the classifier.txt file so I can see what cell definitions it has generated from the data?

**Comment by hpliner** [comment]
Hello, Unfortunately Garnett doesn't have a way to incorporate bulk RNA-seq... I think the only recommendation I could give on that would be to run differential expression analyses with the bulk and see if you find good marker genes that way.

I can be more helpful on the other question. A new marker file isn't created with marker-free training, but you can see which genes the classifier has chosen using the function get_feature_genes. Info on usage is here: https://cole-trapnell-lab.github.io/garnett/docs_m3/#viewing-the-classification-genes

Good luck with the classifying!

**Comment by AlexCocker** [comment]
Thank you very much! I will follow your advice and pull the differentially expressed genes and see how incorporating them with the get_feature_genes from the trained classifier goes :)
