### ISSUE TITLE
Force assignment to all cells?

### ISSUE THREAD

**Issue by igrabski** [cole-trapnell-lab/garnett#57]
Hi all,

I have a question about classifying cells -- is it possible to turn off the functionality to flag some cells as "unassigned," or in other words, to force all cells to be assigned a cell-type label? I see that the sensitivity with which a cell is marked unassigned can be toggled through the rank_prob_ratio parameter, but it seems that this parameter must always be greater than 1, whereas all cells would only be forced to be assigned a label if this parameter were equal to 1 (if I understand it correctly). Please let me know!

Thanks so much.

**Comment by hpliner** [comment]
Hello, Apologies for the delay. Unfortunately, at this time there isn't a way to do this - the idea being that if the rank_prob_ratio was equal to 1, then there would be multiple cell types that were equally likely to be assigned.

**Comment by hpliner** [comment]
I'm going to go ahead an close, reopen if you have further issues
