### ISSUE TITLE
Getting started with Garnett

### ISSUE THREAD

**Issue by mommymisato** [cole-trapnell-lab/garnett#59]
@hpliner This is probably a long shot. But, I recently got started in Bioinformatics and I was assigned to learn how to use Garnett and UMAP. I went through the tutorial and the loading of the data, to train the classifier wasnt very clear to me as I still dont super understand coding much less R. Would there be any chance you could upload a youtube vid explaining it.

Thanks,
B

**Comment by hpliner** [comment]
Hello,

Unfortunately I won't be able to provide a video on data loading. I can point you to a couple of resources. First, I highly recommend reading the monocle3 tutorials as well - the data object garnett uses is a monocle object and there is much more information on the data object there (https://cole-trapnell-lab.github.io/monocle3/docs/starting/). I can also recommend a couple of analysis tutorials put on by the Brotman Baty: https://www.youtube.com/channel/UCdyFqzKZv4pyjIQ5VW7UIDQ

**Comment by hpliner** [comment]
I'm going to go ahead an close, reopen if you have further issues
