### ISSUE TITLE
Run time to train new classifier

### ISSUE THREAD

**Issue by lwtan90** [cole-trapnell-lab/garnett#61]
Hi,

Thank you for creating the tool.
I am trying to build new classifier using a total of 100 markers using a total of 5000 cells (train_cell_classifier). 
I wonder how long it will take usually because currently it has been stagnant at the stage of "There are 9 cell type definitions".
Thank you.

Wilson

**Comment by hpliner** [comment]
Hi, 
Sounds like something has gone wrong here, going from the message you quoted to the list of example cells found should be quite quick (a few minutes max). Can you try running the example on the website? Does that work ok? https://cole-trapnell-lab.github.io/garnett/docs_m3/#1b-train-your-own-classifier

**Comment by hpliner** [comment]
Closing, reopen if this remains an issue
